version: '3.8'

services:
  app:
    container_name: ${APP_NAME}_app
    restart: always
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
        - ${LARAVEL_PORT:-80}:80
    volumes:
      - '.:/var/www/html'
    networks:
      - ${APP_NAME}_network

  mysqlsrv:
    container_name: ${APP_NAME}_db
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE}'
    ports:
      - ${DB_PORT_DOCKER:-3306}:3306
    volumes:
      - './docker/db-data:/var/lib/mysql'
    networks:
      - ${APP_NAME}_network

networks:
  creadisis-app_network:
    name: ${APP_NAME}_network
    driver: bridge
